### ISSUE TITLE
Nicks not being escape for regular  expression usage

### ISSUE THREAD

**Issue by gotwf** [eqyiel/circe-notifications#2]
This seems to be a problem with nicks not being escape for regular expression usage.  Backtrace attached.

[circe-backtrace-no-znc.txt](https://github.com/eqyiel/circe-notifications/files/261790/circe-backtrace-no-znc.txt)

P.S.; wasamasa and forcer helped track this down in event you desire further info/clarification and I am afk.

**Comment by eqyiel** [comment]
Thanks for letting me know.

It looks like this was a consequence of using `string-match` for usernames without quoting regexp characters:

https://github.com/eqyiel/circe-notifications/blob/87312561aaa80c2812e5e308f8a88e117e60dcae/circe-notifications.el#L275

I think I've fixed it now, could you please try the version on master?

**Comment by gotwf** [comment]
Hey thanks bunches for the patch.  Sorry for the delayed response.

A quick test and it seems to be working correctly.  I've not yet tested against all the strange special char nicks that various trolls have become so fond of lately but will let you know.

**Comment by eqyiel** [comment]
Thanks for your assistance!
