### ISSUE TITLE
`circe-notifications-nicks-on-all-networks` is broken

### ISSUE THREAD

**Issue by chrisbarrett** [eqyiel/circe-notifications#5]
This function indexes into the list of network options to extract the user's nicks. It would be better to use `plist-get` instead of relying on the order in which properties are defined.

What is the expected return type of this function? If it just needs to be a set of nicknames, this would work:

``` lisp
(defun circe-notifications-nicks-on-all-networks ()
  "Get a list of all nicks in use according to `circe-network-options'."
  (delete-dups (mapcar (lambda (opt)
                          (plist-get (cdr opt) :nick))
                        circe-network-options)))
```

Related to #4.

**Comment by eqyiel** [comment]
Thanks, that looks a lot nicer!  It's on master now.

I don't see how it relates to #4 yet though, could you tell me more?

**Comment by chrisbarrett** [comment]
On that ticket, @soupault pasted in a backtrace with error lines that include the following message:

> Error running event nil handler circe--irc-display-event: (wrong-type-argument stringp t)

I assume this error is the same one I had, which is really thrown by `string-match` getting passed `t` instead of a string representing a user's nick.

The old implementation was indexing into each element in `circe-network-options`. Those elements are basically plists with the network name consed in front (if you squint, it's actually an alist from a network name to an options plist). By indexing rather than looking up by key, the values returned depended on the order of elements in those plists.

For me, the implementation was pulling `t` constants out of the plist and setting `circe-notifications-watch-strings` to something like `'(t t t t)`. The functions that depend on this variable would then pass the values on to functions expecting strings, causing errors in the message handler functions.

**Comment by eqyiel** [comment]
Yikes.  Thanks for your assistance!

**Comment by soupault** [comment]
Thanks for your help @chrisbarrett !
