### ISSUE TITLE
Please tag a 'stable' version for melpa-stable

### ISSUE THREAD

**Issue by gotwf** [eqyiel/circe-notifications#6]
Because otherwise one must also pull in 'unstable' versions of alert and its dependencies. 

Thx bunches ;)

**Comment by eqyiel** [comment]
Sure!

https://github.com/eqyiel/circe-notifications/tree/1.0

I may have done this correctly.  Let me know!

**Comment by gotwf** [comment]
Yep.  Thank you.

**Comment by eqyiel** [comment]
Great!
